#!/usr/bin/env bash

source "app/dxraft"

_cdepl_kill_application() {
    local cluster_total_nodes=$(cdepl_cluster_get_alloc_node_count)
	cdepl_app_dxraft_node_cleanup 0 $((cluster_total_nodes - 1))
}
