#!/usr/bin/env bash

source "app/dxraft"

_cdepl_run_application()
{
    local cluster_total_nodes=$(cdepl_cluster_get_alloc_node_count)

	# Initialize dxraft deployment
	cdepl_app_dxraft_init "$(cdepl_cluster_application_install_dir)"

	# Kill any still running instances from previous deployments
	cdepl_app_dxraft_node_cleanup 0 $(($cluster_total_nodes - 1))

	# Start all nodes
	cdepl_app_dxraft_start_node 0 $(($cluster_total_nodes - 1))
}
