#!/usr/bin/env bash

source "app/dxraft"

_cdepl_run_application()
{
    local cluster_total_nodes=$(cdepl_cluster_get_alloc_node_count)
    local log_level="info"

	PARAMS=""
	while (( "$#" )); do
	case "$1" in
		--log-level)
			server_count="$2"
			shift 2
			;;
		--) # end argument parsing
			shift
			break
			;;
		-*|--*=) # unsupported flags
			echo "Error: Unsupported flag $1" >&2
			exit 1
			;;
		*) # preserve positional arguments
			PARAMS="$PARAMS $1"
			shift
			;;
	esac
	done

	# Initialize dxraft deployment
	cdepl_app_dxraft_init "$(cdepl_cluster_application_install_dir)/dxraft" "$log_level"

	# Kill any still running instances from previous deployments
	cdepl_app_dxraft_node_cleanup 0 $(($cluster_total_nodes - 1))

	# Start all nodes
	cdepl_app_dxraft_start_node 0 $(($cluster_total_nodes - 1))
}
